# Generated by Django 4.2.4 on 2023-09-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="UserModel",),
    ]
