# Generated by Django 4.2.4 on 2023-09-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_amount", models.IntegerField()),
                ("expense_type", models.CharField(max_length=30)),
                ("expense_date", models.DateField()),
                ("expense_description", models.TextField(max_length=30)),
            ],
            options={"db_table": "expense",},
        ),
    ]
