# Generated by Django 4.2.4 on 2023-09-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IncomeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("income_amount", models.IntegerField()),
                ("income_type", models.CharField(max_length=30)),
                ("income_date", models.DateField()),
                ("income_description", models.TextField(max_length=30)),
            ],
            options={"db_table": "income",},
        ),
    ]
